services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "5432:3306"  # Cambia el puerto 5432 (host) -> 3306 (contenedor)
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mi_red

  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge

volumes:
  mysql-data:
