services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "5432:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "8080:80"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mysql-network

  app:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    ports:    
      - 3000:3000
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
